Added update command
Running the command makes the script can update itself

diff --git a/simple-docker-run b/simple-docker-run
--- a/simple-docker-run
+++ b/simple-docker-run
@@ -35,10 +35,12 @@ simple_docker_run_usage() {
 	# :command.usage_commands
 	printf "%s\n" "Commands:"
 	printf "  %s   Generate bash completions\n" "completions"
-	printf "  %s   Create a docker contaner\n" "create     "
-	printf "  %s   Run a created docker contaner interactively\n" "run        "
-	printf "  %s   Remove a created docker contaner\n" "remove     "
+	printf "  %s   Create a docker container\n" "create     "
+	printf "  %s   List available containers\n" "list       "
+	printf "  %s   Run a created docker container interactively\n" "run        "
+	printf "  %s   Remove a created docker container\n" "remove     "
 	printf "  %s   Uninstall this script\n" "uninstall  "
+	printf "  %s   Update this script\n" "update     "
 	echo
 
 	# :command.long_usage
@@ -91,17 +93,17 @@ simple_docker_run_completions_usage() {
 # :command.usage
 simple_docker_run_create_usage() {
 	if [[ -n $long_usage ]]; then
-		printf "simple-docker-run create - Create a docker contaner\n"
+		printf "simple-docker-run create - Create a docker container\n"
 		echo
 
 	else
-		printf "simple-docker-run create - Create a docker contaner\n"
+		printf "simple-docker-run create - Create a docker container\n"
 		echo
 
 	fi
 
 	printf "%s\n" "Usage:"
-	printf "  simple-docker-run create CONTAINER_NAME SOURCE_IMAGE\n"
+	printf "  simple-docker-run create CONTAINER_NAME SOURCE_IMAGE [DOCKER_RECIPE]\n"
 	printf "  simple-docker-run create --help | -h\n"
 	echo
 
@@ -127,6 +129,11 @@ simple_docker_run_create_usage() {
 		printf "    Base image to use\n"
 		echo
 
+		# :argument.usage
+		printf "  %s\n" "DOCKER_RECIPE"
+		printf "    Docker commands to add to the base recipe\n"
+		echo
+
 		# :command.usage_examples
 		printf "%s\n" "Examples:"
 		printf "  simple-docker-run create linux_builder debian:11\n"
@@ -136,13 +143,47 @@ simple_docker_run_create_usage() {
 }
 
 # :command.usage
-simple_docker_run_run_usage() {
+simple_docker_run_list_usage() {
 	if [[ -n $long_usage ]]; then
-		printf "simple-docker-run run - Run a created docker contaner interactively\n"
+		printf "simple-docker-run list - List available containers\n"
 		echo
 
 	else
-		printf "simple-docker-run run - Run a created docker contaner interactively\n"
+		printf "simple-docker-run list - List available containers\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  simple-docker-run list\n"
+	printf "  simple-docker-run list --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+		# :command.usage_examples
+		printf "%s\n" "Examples:"
+		printf "  simple-docker-run list\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+simple_docker_run_run_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "simple-docker-run run - Run a created docker container interactively\n"
+		echo
+
+	else
+		printf "simple-docker-run run - Run a created docker container interactively\n"
 		echo
 
 	fi
@@ -186,11 +227,11 @@ simple_docker_run_run_usage() {
 # :command.usage
 simple_docker_run_remove_usage() {
 	if [[ -n $long_usage ]]; then
-		printf "simple-docker-run remove - Remove a created docker contaner\n"
+		printf "simple-docker-run remove - Remove a created docker container\n"
 		echo
 
 	else
-		printf "simple-docker-run remove - Remove a created docker contaner\n"
+		printf "simple-docker-run remove - Remove a created docker container\n"
 		echo
 
 	fi
@@ -253,7 +294,41 @@ simple_docker_run_uninstall_usage() {
 
 		# :command.usage_examples
 		printf "%s\n" "Examples:"
-		printf "  simple-docker-run uninstall linux_builder\n"
+		printf "  simple-docker-run uninstall\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+simple_docker_run_update_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "simple-docker-run update - Update this script\n"
+		echo
+
+	else
+		printf "simple-docker-run update - Update this script\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  simple-docker-run update\n"
+	printf "  simple-docker-run update --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+		# :command.usage_examples
+		printf "%s\n" "Examples:"
+		printf "  simple-docker-run update\n"
 		echo
 
 	fi
@@ -326,6 +401,18 @@ function script_uninstall_itself {
 		shred -u "$SCRIPT_PATH"
 }
 
+# src/lib/script_update_itself.sh
+SCRIPT_BASE_DIR="$HOME/.local/bin"
+SCRIPT_PATH="$SCRIPT_BASE_DIR/simple-docker-run"
+
+function script_update_itself {
+		# Download script and place it into local bin
+		mkdir -p "$SCRIPT_BASE_DIR"
+		curl https://raw.githubusercontent.com/Tomiyou/docker_image_runner/master/simple-docker-run --output "$SCRIPT_PATH"
+		chmod +x "$SCRIPT_PATH"
+		echo "Script updated"
+}
+
 # src/lib/send_completions.sh
 send_completions() {
 	echo $'# simple-docker-run completion                             -*- shell-script -*-'
@@ -374,12 +461,20 @@ send_completions() {
 	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "$(docker ps -a --filter "label=simple_docker_run" --format \'{{.Names}}\' 2> /dev/null) --help -h")" -- "$cur" )'
 	echo $'      ;;'
 	echo $''
+	echo $'    \'update\'*)'
+	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+	echo $'      ;;'
+	echo $''
+	echo $'    \'list\'*)'
+	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+	echo $'      ;;'
+	echo $''
 	echo $'    \'run\'*)'
 	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "$(docker ps -a --filter "label=simple_docker_run" --format \'{{.Names}}\' 2> /dev/null) --help -h")" -- "$cur" )'
 	echo $'      ;;'
 	echo $''
 	echo $'    *)'
-	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help --version -h -v completions create remove run uninstall")" -- "$cur" )'
+	echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help --version -h -v completions create list remove run uninstall update")" -- "$cur" )'
 	echo $'      ;;'
 	echo $''
 	echo $'  esac'
@@ -411,12 +506,14 @@ simple_docker_run_create_command() {
 
 	get_container_image_name "${args[container_name]}"
 	SOURCE_IMAGE="${args[source_image]}"
+	DOCKER_RECIPE="${args[docker_recipe]}"
 
 	# Create temporary Dockerfile
 	TMP_DOCKERFILE="/tmp/simple_docker_run_$(date +%s)"
 	touch "$TMP_DOCKERFILE"
 
 	cat > "$TMP_DOCKERFILE" <<- EOF
+
 	FROM $SOURCE_IMAGE
 
 	# Label tells us which containers were created by this script
@@ -425,9 +522,19 @@ simple_docker_run_create_command() {
 	RUN apt-get update
 	RUN apt-get install -y git fakeroot build-essential ncurses-dev \\
 			xz-utils libssl-dev bc flex libelf-dev bison gcc llvm clang curl \\
-			wget vim
+			wget vim sudo
 
+	EOF
+
+	# append docker recipe to the general recipe we have above
+	[ -e "$DOCKER_RECIPE" ] && cat "$DOCKER_RECIPE" >> "$TMP_DOCKERFILE"
+
+	cat >> "$TMP_DOCKERFILE" <<- EOF
+
+	# Add new user
 	RUN useradd --create-home --shell /bin/bash $CURRENT_USER
+	RUN echo "password123" | passwd $CURRENT_USER --stdin
+	RUN usermod -aG sudo $CURRENT_USER
 	USER $CURRENT_USER
 	WORKDIR /home/$CURRENT_USER
 
@@ -447,6 +554,14 @@ simple_docker_run_create_command() {
 	docker run --name $CONTAINER_NAME --tty --interactive \
 			-v "$CURRENT_PATH:/home/$CURRENT_USER/$CURRENT_DIRECTORY" \
 			$IMAGE_NAME
+
+}
+
+# :command.function
+simple_docker_run_list_command() {
+	# src/list_command.sh
+	echo "Avaliable containers:"
+	docker ps -a --filter "label=simple_docker_run" --format '{{.Names}}'
 
 }
 
@@ -498,6 +613,16 @@ simple_docker_run_uninstall_command() {
 
 }
 
+# :command.function
+simple_docker_run_update_command() {
+	# src/update_command.sh
+
+	# Script will update itself
+
+	trap script_update_itself EXIT
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
 	# :command.fixed_flags_filter
@@ -543,6 +668,13 @@ parse_requirements() {
 			shift $#
 			;;
 
+		list)
+			action="list"
+			shift
+			simple_docker_run_list_parse_requirements "$@"
+			shift $#
+			;;
+
 		run)
 			action="run"
 			shift
@@ -561,6 +693,13 @@ parse_requirements() {
 			action="uninstall"
 			shift
 			simple_docker_run_uninstall_parse_requirements "$@"
+			shift $#
+			;;
+
+		update)
+			action="update"
+			shift
+			simple_docker_run_update_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -690,6 +829,10 @@ simple_docker_run_create_parse_requirements() {
 
 					args['source_image']=$1
 					shift
+				elif [[ -z ${args['docker_recipe']+x} ]]; then
+
+					args['docker_recipe']=$1
+					shift
 				else
 					printf "invalid argument: %s\n" "$key" >&2
 					exit 1
@@ -702,13 +845,59 @@ simple_docker_run_create_parse_requirements() {
 
 	# :command.required_args_filter
 	if [[ -z ${args['container_name']+x} ]]; then
-		printf "missing required argument: CONTAINER_NAME\nusage: simple-docker-run create CONTAINER_NAME SOURCE_IMAGE\n" >&2
+		printf "missing required argument: CONTAINER_NAME\nusage: simple-docker-run create CONTAINER_NAME SOURCE_IMAGE [DOCKER_RECIPE]\n" >&2
 		exit 1
 	fi
 	if [[ -z ${args['source_image']+x} ]]; then
-		printf "missing required argument: SOURCE_IMAGE\nusage: simple-docker-run create CONTAINER_NAME SOURCE_IMAGE\n" >&2
+		printf "missing required argument: SOURCE_IMAGE\nusage: simple-docker-run create CONTAINER_NAME SOURCE_IMAGE [DOCKER_RECIPE]\n" >&2
 		exit 1
 	fi
+
+}
+
+# :command.parse_requirements
+simple_docker_run_list_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				simple_docker_run_list_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.dependencies_filter
+
+	# :command.command_filter
+	action="list"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
 
 }
 
@@ -878,6 +1067,52 @@ simple_docker_run_uninstall_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+simple_docker_run_update_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				simple_docker_run_update_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.dependencies_filter
+
+	# :command.command_filter
+	action="update"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
 # :command.initialize
 initialize() {
 	version="0.1.0"
@@ -919,6 +1154,15 @@ run() {
 			fi
 			;;
 
+		"list")
+			if [[ ${args['--help']:-} ]]; then
+				long_usage=yes
+				simple_docker_run_list_usage
+			else
+				simple_docker_run_list_command
+			fi
+			;;
+
 		"run")
 			if [[ ${args['--help']:-} ]]; then
 				long_usage=yes
@@ -943,6 +1187,15 @@ run() {
 				simple_docker_run_uninstall_usage
 			else
 				simple_docker_run_uninstall_command
+			fi
+			;;
+
+		"update")
+			if [[ ${args['--help']:-} ]]; then
+				long_usage=yes
+				simple_docker_run_update_usage
+			else
+				simple_docker_run_update_command
 			fi
 			;;
 
