Semi working Bash completion

diff --git a/simple-docker-run b/simple-docker-run
--- a/simple-docker-run
+++ b/simple-docker-run
@@ -34,10 +34,11 @@ simple_docker_run_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Create a docker contaner\n" "create   "
-  printf "  %s   Run a created docker contaner interactively\n" "run      "
-  printf "  %s   Remove a created docker contaner\n" "remove   "
-  printf "  %s   Uninstall this script\n" "uninstall"
+  printf "  %s   Generate bash completions\n" "completions"
+  printf "  %s   Create a docker contaner\n" "create     "
+  printf "  %s   Run a created docker contaner interactively\n" "run        "
+  printf "  %s   Remove a created docker contaner\n" "remove     "
+  printf "  %s   Uninstall this script\n" "uninstall  "
   echo
 
   # :command.long_usage
@@ -50,6 +51,38 @@ simple_docker_run_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+simple_docker_run_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "simple-docker-run completions\n"
+    echo
+
+    printf "  Generate bash completions\n  Usage: eval \"\$(simple-docker-run completions)\"\n"
+    echo
+
+  else
+    printf "simple-docker-run completions - Generate bash completions\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  simple-docker-run completions\n"
+  printf "  simple-docker-run completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -303,7 +336,81 @@ function remove_image_from_cache {
   sed -i "/$1/d" "$LOCAL_CACHE/image_cache"
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# simple-docker-run completion                             -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_simple-docker-run_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_simple-docker-run_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'uninstall\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'create\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'remove\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'run\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_simple-docker-run_completions_filter "--help --version -h -v create remove run uninstall")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _simple-docker-run_completions simple-docker-run'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
+# :command.function
+simple_docker_run_completions_command() {
+  # src/completions_command.sh
+  # Call the `send_completions` function which was added by running:
+  #
+  #   $ bashly add completions
+  #
+  # Users can now enable bash completion for this script by running:
+  #
+  #   $ eval "$(cli completions)"
+  #
+  send_completions
+
+}
+
 # :command.function
 simple_docker_run_create_command() {
   # src/create_command.sh
@@ -425,6 +532,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completions)
+      action="completions"
+      shift
+      simple_docker_run_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
     create)
       action="create"
       shift
@@ -465,6 +579,52 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+simple_docker_run_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        simple_docker_run_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -730,7 +890,7 @@ initialize() {
   # src/initialize.sh
 
   CURRENT_USER="$(whoami)"
-  LOCAL_CACHE="/home/$CURRENT_USER/.local/share/simple_docker_run"
+  LOCAL_CACHE="$HOME/.local/share/simple_docker_run"
 
   mkdir -p "$LOCAL_CACHE"
 
@@ -746,6 +906,15 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "completions")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        simple_docker_run_completions_usage
+      else
+        simple_docker_run_completions_command
+      fi
+      ;;
+
     "create")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
